---
- name: Provisionamiento del servidor elasticsearch
  hosts: "elastic"
  become: true
  become_user: root
  vars_files:
      - vars/elastic.yml

  roles:
      - role: geerlingguy.ntp
        ntp_timezone: Europe/Madrid

      - role: ansible-elasticsearch

  post_tasks:
      - name: Reiniciar cron por el cambio de zona horaria
        service:
          name: cron
          state: restarted